@machine-1 = server-rack-01
@machine-2 = server-rack-02
@cpu_usage = CPU_USAGE
@ram_usage = RAM_USAGE
@hdd_usage = DISK_USAGE

## Add a metric
POST {{api_endpoint}}/api/metric/add
Accept: application/json
Content-Type: application/json

{
  "machineId": "{{machine-2}}",
  "metricType": "{{cpu_usage}}",
  "value": {{$random.integer(0,100)}},
  "timestamp": {{$timestamp}}
}

####

< {%
    const allMetrics = ["CPU_USAGE", "RAM_USAGE", "DISK_USAGE"];
    const randomMetric = allMetrics[$random.integer(0,3)]
    request.variables.set("metric", randomMetric)
    request.variables.set("id", [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
%}
POST {{api_endpoint}}/api/metric/add
Accept: application/json
Content-Type: application/json

{
  "machineId": "server-rack-{{id}}{{$random.integer(1,9)}}",
  "metricType": "{{metric}}",
  "value": {{$random.integer(0,100)}},
  "timestamp": {{$timestamp}}
}